# Generated by Django 5.0.4 on 2024-04-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
            ],
            options={
                'db_table': 'all_users',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslar.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars_soni', models.IntegerField()),
                ('video_id', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('youtube', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslar.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslar.subcategory')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
    ]
